### ISSUE TITLE
"Note 2 à l'article: " (and Note 3 à l'article: ) still not split into Notes

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#10]
"Note {n} à l'article: " should be split into notes, but now only "Note 1 à l'article: " is split.

**Comment by HassanAkbar** [comment]
This should have been fixed by this commit https://github.com/glossarist/iev-data/commit/a42911a69f1990ebecded87e2349dd4051d5fc44.

Here is the output for the concept `561-01-05`

```yaml
```

**Comment by ronaldtse** [comment]
That's perfect. Thanks!
