### ISSUE TITLE
IEV data anomaly (20201217): REPLACES does not include IEV ref

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#100]
212-11-41 in its REPLACES column has value `2010-06`. Looking at other concepts, it should rather be something like `XXX-YY-ZZ:2010-06`. Please clarify what is the proper value.

Extracted from https://github.com/glossarist/iev-data/issues/34#issuecomment-766092183.

**Comment by ronaldtse** [comment]
Requested clarification from IEC.

**Comment by ronaldtse** [comment]
From IEC:

> Yes, this is just an omission. I have corrected the field to say “212-11-41:2010-06”.

Closing since fixed.

**Comment by ronaldtse** [comment]
Closing first, reopen if necessary.

**Comment by ronaldtse** [comment]
In addition to IEC:

----

> There are several entries in the REPLACES that writes “IEV xxx-xxx-xxx:yyyy-mm” instead of "xxx-xxx-xxx:yyyy-mm”.
> 
> Would you also like to make them consistent in format too? Then all the REPLACES will have the "xxx-xxx-xxx:yyyy-mm” format.
>
> They are:
> 212-11-02
> 212-11-35
> 903-04-14
>
> <img width="673" alt="image001" src="https://user-images.githubusercontent.com/11865/106306922-aaccd100-6299-11eb-9390-a5376cd3fb6d.png">

--------

From IEC:

> All corrected.

**Comment by skalee** [comment]
Got it, thanks!
