### ISSUE TITLE
Update to use latest Glossarist gem

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#202]

**Comment by ronaldtse** [comment]
Let's use a new gem name like glossarist-new for now, thanks.

**Comment by ronaldtse** [comment]
@HassanAkbar this is done, right?

**Comment by HassanAkbar** [comment]
@ronaldtse Yes this has been done in #204

**Comment by ronaldtse** [comment]
Closing, thanks! Please help close any other completed issues too.
