### ISSUE TITLE
Support Ruby 3.1

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#209]
Now that #207 implements Ruby 3.0 support, perhaps 3.1 is just minor step ahead.

**Comment by HassanAkbar** [comment]
This link is not working and the `iev-data` conversion is breaking.
https://webstore.iec.ch/searchkey&type=wr&RefNbr=IEC%206&From=&To=&start=1 It says the the site is down for maintenance.

If we change the type or RefNbr it works fine. for example something like this will work fine
https://webstore.iec.ch/searchkey&type=wr&RefNbr=IEC%2062&From=&To=&start=1

Do you know what could be wrong here?

**Comment by ronaldtse** [comment]
@HassanAkbar it might mean that the results are too numerous? IEC%206 means "IEC 6", and all IEC standards start with "6xxxx" (this is an agreement between IEC and ISO, all IEC standards start with 6).

**Comment by ronaldtse** [comment]
Question: why are we querying the endpoint with "IEC 6"?

**Comment by ronaldtse** [comment]
@HassanAkbar you might want to check the XHRs from this page:
https://webstore.iec.ch/searchform&q=60050

I believe that's where the URL came for.

**Comment by HassanAkbar** [comment]
Actually the `source` value in file is `definition 3.60 of 62127-1` but the regex in `iev-data` is picking only the first digit i.e `6` so just want to make sure that is this intentional or is this a bug in `iev-data`?

**Comment by ronaldtse** [comment]
Definitely a bug 😉
