### ISSUE TITLE
Verify the correctness of parsed iev-data

### ISSUE THREAD

**Issue by HassanAkbar** [glossarist/iev-data#212]
Check if the parsed data is accurate and free of errors.

**Comment by HassanAkbar** [comment]
The definition of `112-04-01` in `English` is

> process of experimentally obtaining one or more values that can reasonably be attributed to a quantity
<NOTE 1 – Measurement does not apply to nominal properties.
<NOTE 2 – Measurement implies comparison of quantities, including counting of entities.
<NOTE 3 – The French word “mesure” has several meanings in everyday French language. It is for this reason that the French word “mesurage” has been introduced to describe the act of measurement. Nevertheless, the French word “mesure” occurs many times in forming terms, following current usage, and without ambiguity. Examples are: unité de mesure (unit of measurement), méthode de mesure (measurement method), instrument de mesure (measurement instrument). This does not mean that the use of the French word “mesurage” in place of “mesure” in such terms is not permissible when advantageous.

@ronaldtse The question is when converting it to a glossarist object, should the examples in `NOTE 3` go into the `examples` or stay in the `note` field?

**Comment by ronaldtse** [comment]
These are clearly 3 separate notes, so they should go into the notes array as 3 separate items inside the Glossarist object.

**Comment by ronaldtse** [comment]
Ah, the examples in Note 3 stay in the note.

**Comment by HassanAkbar** [comment]
How should we differentiate between the above and `112-01-33` which is

> ratio of two units of measurement for quantities of the same kind 
<NOTE 1 – An example of conversion factor is km/m = 1 000 and thus 1 km = 1 000 m
<NOTE 2 – The units may belong to different system of units. Examples are:<br>
• h/s = 3 600 and thus 1 h = 3 600 s;<br>
• (km/h)/(m/s) = (km/m)/(h/s) = (1 000/3 600) = (1/3,6), and thus 1 km/h = (1/3,6) m/s.

In this case, the examples seem to be of the concept. So how do we differentiate between the above concept where text after `Examples are:` should stay with the note and in this concept where text after `Examples are:` should go into `examples`?

**Comment by ronaldtse** [comment]
@HassanAkbar in the latter example, they are meant to also stay with the note. It is incorrect to separate them -- they are examples of what the Note says, not the concept itself.

**Comment by HassanAkbar** [comment]
OK, Got it.
