### ISSUE TITLE
IEV data structures: parse all SYNONYM{1,2,3}STATUS

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#32]
```
<símbolo>
Admitted
Deprecated
Preferred
obsoleto
prąd startowy
НАПУШТЕН
```

**Comment by ronaldtse** [comment]
Place to edit:
https://github.com/glossarist/iev-data/blob/f777f00f09b1d6edb3a326b5bd71ed58e461e327/lib/iev/termbase/term.rb#L184-L196

(the text like `suositeltava` that doesn't exist in this data set can be removed, they are remaining from the TC 211 parser)

**Comment by skalee** [comment]
"prąd startowy" is a sure bug, see #61

**Comment by skalee** [comment]
Synonym statuses are now handled with exactly the same class as main term status. Although it's possible there are some deficiencies, this issue become more like a duplicate. Closing.
