### ISSUE TITLE
IEV data anomaly (20201217): 811-13-10 pl SYNONYM1STATUS wrong value (prąd startowy)

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#61]
Term 811-13-10 pl has „prąd startowy” in column G (SYNONYM1STATUS) which is surely a synonym rather than its status. Clarification from IEV probably needed.

**Comment by ronaldtse** [comment]
Clarification sought from IEC.

**Comment by ronaldtse** [comment]
> Corrected

Was:
![image002](https://user-images.githubusercontent.com/11865/106231663-2d6b7700-622d-11eb-8da4-2a643440b1ba.jpg)

Now:
![Uploading image006.jpg…]()

Source data confirmed fixed, closing.
