### ISSUE TITLE
Migrate to Ruby 3.0

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#79]
Ruby 3.0 brings significant performance boost. Migration is expected to be simple, and this gem should greatly benefit from that.

**Comment by ronaldtse** [comment]
Agree especially since this gem is not used downstream and will not affect others.

**Comment by skalee** [comment]
This requires changes in some or all Relaton gems, typically because of https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/. I've started experimenting already: https://github.com/relaton/relaton-bib/pull/38, but I presume other Relaton gems need to be fixed too. Also some development dependencies aren't compatible with Ruby 3 yet.

**Comment by ronaldtse** [comment]
This is resolved in #207
