### ISSUE TITLE
Unnecessary colons in source relationships

### ISSUE THREAD

**Issue by skalee** [glossarist/iev-data#86]
For example, 112-01-01:

```
  authoritative_source:
  - ref: ISO/IEC Guide 99:2007
    clause: '1.1'
    link: https://www.iso.org/standard/45324.html
    relationship:
      :type: :modified
      :modification: Suppression de NOTE 3 et NOTE 4, et quelques modifications dans
        les autres.
    original: ISO/IEC Guide 99:2007, 1.1, modifié – Suppression de NOTE 3 et NOTE
      4, et quelques modifications dans les autres.
  review_decision_event: published
```

Note that `:type:` and `:modification:` field names start with a colon.

**Comment by ronaldtse** [comment]
@skalee yes this is kind of a bug -- if we encoded the "type" and "modifications" keys as strings we won't have double colons.

**Comment by skalee** [comment]
Yes, it's caused by using symbols, not strings as hash keys. BTW perhaps the best option would be to stringify keys just before writing concepts to files. I need to think about it.
